// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmmvbxgsniybuvlbhuvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtbXZieGdzbml5YnV2bGJodXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTI0NzksImV4cCI6MjA2ODg2ODQ3OX0.XsvlwpfPwEPFnOjKALBiKMR1t7K8_sRFz5OEQ5jvnW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});